{
  "openapi": "3.0.0",
  "info": {
    "title": "GlueX Router v1 API",
    "version": "1.0.0",
    "description": "API for interacting with the GlueX Router v1."
  },
  "servers": [
    {
      "url": "https://router.gluex.xyz",
      "description": "Production"
    }
  ],
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key"
      }
    },
    "schemas": {
      "PriceRequest": {
        "type": "object",
        "properties": {
          "inputToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "outputToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "inputAmount": { "type": "integer" },
          "userAddress": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "outputReceiver": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "chainID": { "type": "string" },
          "uniquePID": { "type": "string" }
        },
        "required": [
          "inputToken",
          "outputToken",
          "inputAmount",
          "userAddress",
          "outputReceiver",
          "chainID",
          "uniquePID"
        ]
      },
      "PriceResponse": {
        "type": "object",
        "properties": {
          "inputToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "outputToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "feeToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "outputReceiver": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "inputAmount": { "type": "integer" },
          "outputAmount": { "type": "integer" },
          "partnerFee": { "type": "integer" },
          "routingFee": { "type": "integer" },
          "effectiveOutputAmount": { "type": "integer" },
          "minOutputAmount": { "type": "integer" },
          "liquidityModules": {
            "type": "array",
            "items": { "type": "string" }
          }
        }
      },
      "QuoteRequest": {
        "type": "object",
        "properties": {
          "inputToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "outputToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "inputAmount": { "type": "integer" },
          "userAddress": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "outputReceiver": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "chainID": { "type": "string" },
          "uniquePID": { "type": "string" },
          "isPermit2": { "type": "boolean" }
        },
        "required": [
          "inputToken",
          "outputToken",
          "inputAmount",
          "userAddress",
          "outputReceiver",
          "chainID",
          "uniquePID",
          "isPermit2"
        ]
      },
      "QuoteResponse": {
        "type": "object",
        "properties": {
          "inputToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "outputToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "feeToken": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "outputReceiver": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "inputAmount": { "type": "integer" },
          "outputAmount": { "type": "integer" },
          "partnerFee": { "type": "integer" },
          "routingFee": { "type": "integer" },
          "effectiveOutputAmount": { "type": "integer" },
          "minOutputAmount": { "type": "integer" },
          "liquidityModules": {
            "type": "array",
            "items": { "type": "string" }
          },
          "router": { "type": "string", "pattern": "^0x[a-fA-F0-9]{40}$" },
          "calldata": { "type": "string" }
        }
      }
    }
  },
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "paths": {
    "/liquidity": {
      "get": {
        "summary": "Retrieve available chains and liquidity modules",
        "description": "Fetches a list of supported blockchain networks and their associated liquidity modules.",
        "responses": {
          "200": {
            "description": "Successful response containing available chains and liquidity modules.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "chains": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "chainID": {
                            "type": "string",
                            "description": "Identifier of the blockchain network."
                          },
                          "networkID": {
                            "type": "integer",
                            "description": "Numeric identifier for the blockchain network."
                          }
                        }
                      }
                    },
                    "liquidityModules": {
                      "type": "object",
                      "additionalProperties": {
                        "type": "array",
                        "items": { "type": "string" }
                      },
                      "description": "Mapping of chain IDs to their supported liquidity modules."
                    }
                  }
                },
                "example": {
                  "chains": [
                    {"chainID": "base", "networkID": 8453},
                    {"chainID": "ethereum", "networkID": 1}
                  ],
                  "liquidityModules": {
                    "base": ["aerodrome", "alienbase_v2", "maverick_v2"],
                    "ethereum": ["aave_v3", "affine_ultreths_eth", "apeswap"]
                  }
                }                
              }
            }
          },
          "400": {
            "description": "Invalid request payload"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/create": {
      "post": {
        "summary": "Create an API key for a partner",
        "parameters": [
          {
            "in": "header",
            "name": "x-api-key",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["partnerName", "partnerAddress", "partnerFee"],
                "properties": {
                  "partnerName": {
                    "type": "string",
                    "description": "Name of the partner requesting the API key."
                  },
                  "partnerAddress": {
                    "type": "string",
                    "pattern": "^0x[a-fA-F0-9]{40}$",
                    "description": "Wallet address of the partner where the fee can be transferred, if applicable."
                  },
                  "partnerFee": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 4,
                    "description": "Fee specified by the partner. Must be a non-negative integer within the range [0, 4]."
                  }
                }
              },
              "example": {
                "partnerName": "XYZ-Company",
                "partnerAddress": "0x174F75176b73124627116653085Ce9585E261388",
                "partnerFee": 0
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "API key created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": { "type": "string" },
                    "uniquePID": { "type": "string" },
                    "apikey": { "type": "string" }
                  }
                },
                "example": {
                  "statusCode": 200,
                  "body": {
                    "message": "API key created successfully.",
                    "uniquePID": "d70a4570b6129b7ceab95ceb1f2473fbff15b741ea172d02eb533cd2d330b567",
                    "apikey": "HywnZvSlWvrbDbPjA2sDkt7ISqIZSrGd"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request payload"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/v1/price": {
      "post": {
        "summary": "Get swap price without calldata",
        "parameters": [
          {
            "in": "header",
            "name": "x-api-key",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/PriceRequest" },
              "example": {
                "inputToken": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
                "outputToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                "inputAmount": 20000000000,
                "userAddress": "0x9A6D76cB905Df126832AEB1802A27a1b37a6e872",
                "outputReceiver": "0x9A6D76cB905Df126832AEB1802A27a1b37a6e872",
                "chainID": "ethereum",
                "uniquePID": "{your_unique_partner_id}"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Price response",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/PriceResponse" },
                "example": {
                  "statusCode": 200,
                  "result": {
                    "inputToken": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
                    "outputToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                    "feeToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                    "outputReceiver": "0x9A6D76cB905Df126832AEB1802A27a1b37a6e872",
                    "inputAmount": 20000000000,
                    "outputAmount": 6121830800259800326,
                    "partnerFee": 0,
                    "routingFee": 612183080026374,
                    "effectiveOutputAmount": 6121218617179773952,
                    "minOutputAmount": 6118158007871184896,
                    "liquidityModules": [
                      "uniswap_v3"
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request payload"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/v1/quote": {
      "post": {
        "summary": "Get calldata for on-chain swap",
        "parameters": [
          {
            "in": "header",
            "name": "x-api-key",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/QuoteRequest" },
              "example": {
                "inputToken": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
                "outputToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                "inputAmount": 20000000000,
                "userAddress": "0x9A6D76cB905Df126832AEB1802A27a1b37a6e872",
                "outputReceiver": "0x9A6D76cB905Df126832AEB1802A27a1b37a6e872",
                "chainID": "ethereum",
                "uniquePID": "{your_unique_partner_id}",
                "isPermit2": false
              }              
            }
          }
        },
        "responses": {
          "200": {
            "description": "Quote response",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/QuoteResponse" },
                "example": {
                  "statusCode": 200,
                  "result": {
                    "inputToken": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
                    "outputToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                    "feeToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                    "outputReceiver": "0x174F75176b73124627116653085Ce9585E261388",
                    "inputAmount": 20000000000,
                    "outputAmount": 6119854428544000000,
                    "partnerFee": 0,
                    "routingFee": 611985442853888,
                    "effectiveOutputAmount": 6119242443101146112,
                    "minOutputAmount": 6116182821879596032,
                    "liquidityModules": [
                      "fluid_dex"
                    ],
                    "router": "0x8a37EeC92DbBaDbA3C44ea9D94d1569A2bd55B80",
                    "calldata": "0xb8039e98..."
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request payload"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    }
  }
}
